Transfer File

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,23 +1,29 @@
 #!/usr/bin/env bash
-# Explains what the code does
-<<<<<<< HEAD
-# Check if the fourth argument is empty
-if [ $
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
-=======
+# Checking for command line arguments
+
+
 # Checking for command-line argument
 if [ $# -lt 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
->>>>>>> 805e219ac722ff8223d2faa11d690b53fae4e524
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
 
-# Assigning Arguments to variables
+# Assigning parameters to variables
 
 path_to_file=$1
 ip=$2
 username=$3
 path_to_ssh_key=$4
 
+# Disable strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/" 
+
+# Checking if the transfer was succesful
+if [ $? -eq 0 ]
+then 
+	echo "FILE WAS SUCCESFULLY TRANSFERED"
+else
+	echo "FILE TRANSFER FAILED"
+fi
